# Generated by Django 4.1.7 on 2023-02-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registrar_alter_participant_qrhash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationnumber', models.CharField(max_length=100)),
                ('qrtext', models.CharField(max_length=200)),
                ('qrhash', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('verifiedby', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='verification_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('registrationnumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('qrtext', models.CharField(max_length=200)),
                ('qrhash', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
